name: Cloudflare Bypass & Telegram Upload

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'যে ওয়েবসাইটের ইউআরএল ভিজিট করতে চান'
        required: true
        default: 'https://example.com'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-state: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyrogram tgcrypto requests yt-dlp

    - name: Start FlareSolverr in Background
      run: |
        docker run -d \
          -p 8191:8191 \
          -e LOG_LEVEL=info \
          --name=flaresolverr \
          ghcr.io/flaresolverr/flaresolverr:latest
        
        # FlareSolverr চালু হওয়ার জন্য ৫ সেকেন্ড অপেক্ষা করা
        sleep 5 

    - name: Run Downloader Script
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        TARGET_URL: ${{ github.event.inputs.target_url }}
      run: python script.py
